# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
# This is version 2 so we can skip all branches except circleci (which may have its own config file).
# Version 2.1 doesn't yet support workflow branch filtering (requiring the filter to be added for every job in the workflow).
version: 2

jobs:
  build:
    branches:
      only:
        - circleci # list of branches to build
    docker:
      # specify the version you desire here
      - image: ucbbar/chisel3-tools
        user: "chisel"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3072m
      TERM: dumb
      SBT_ARGS: "; set ThisBuild / parallelExecution := false; set ThisBuild / fork := false; set ThisBuild / testForkedParallel := false"

    steps:
      - checkout:
          path: chisel-release

      - run:
          command: |
            cd chisel-release
            git submodule sync
            git submodule update --init --recursive


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-firrtl--{{ checksum "chisel-release/firrtl/build.sbt" }}--{{ checksum "chisel-release/firrtl/project/plugins.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-firrtl

      - run: cd chisel-release/firrtl && cat /dev/null | sbt "$SBT_ARGS" "++2.12.10" compile test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sbt
            - ~/.coursier
          key: v1-dependencies-firrtl--{{ checksum "chisel-release/firrtl/build.sbt" }}--{{ checksum "chisel-release/firrtl/project/plugins.sbt" }}
        
      # run tests!
      - run: cd chisel-release/firrtl && cat /dev/null | sbt "$SBT_ARGS" -DminimalResources "++2.12.10" test:test
